name: editorconfig_linting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Editorconfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@v1
