name: meson_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install libwayland-dev libglew-dev libglfw3-dev libglm-dev libudev-dev libinput-dev

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install meson & ninja
        run: pip install meson ninja

      - uses: actions/checkout@v2
        with:
          repository: zigen-project/zigen
          path: zigen

      - uses: actions/checkout@v2
        with:
          repository: recp/cglm
          path: cglm

      - uses: actions/checkout@v2
        with:
          path: main

      - name: Build zigen
        run: meson --prefix=$(pwd)/target build && ninja -C build install
        working-directory: ./zigen
        env:
          CC: clang

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: zigen-build-log
          path: zigen/build/meson-logs/meson-log.txt

      - name: Build cglm
        run: meson --prefix=$(pwd)/target build && ninja -C build install
        working-directory: ./cglm
        env:
          CC: clang

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cglm-build-log
          path: cglm/build/meson-logs/meson-log.txt

      - name: Update PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/$CGLM_PKGCONFIG:$GITHUB_WORKSPACE/$ZIGEN_PKGCONFIG" >> $GITHUB_ENV
        env:
          ZIGEN_PKGCONFIG: zigen/target/lib/x86_64-linux-gnu/pkgconfig
          CGLM_PKGCONFIG: cglm/target/lib/x86_64-linux-gnu/pkgconfig

      - name: Test zen
        run: meson build && ninja -C build test
        working-directory: ./main
        env:
          CC: clang

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: zen-test-log
          path: main/build/meson-logs/testlog.txt
